version: "3.7"
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dinas-pu'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - internal
  elevationmap-app:
    container_name: elevationmap-app
    networks:
      - internal
    build:
      context: ./
      args:
        ENV_NAME: production
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    command: npm run start
    volumes:
      - ./app:/src/app
      - ./index.ts:/src/index.ts
      - ./package.json:/src/package.json
      - ./config:/src/config
      - ./seeders:/src/seeders
      - /src/node_modules
    depends_on:
      - database
networks:
  internal:
    driver: bridge
volumes:
  my-db: null
